# Generated by Django 5.1 on 2024-09-21 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('song_mp3', models.FileField(upload_to='songs/')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2024, 9, 21, 2, 32, 7, 36239))),
                ('artists', models.CharField(default='Various Artists', max_length=1000)),
            ],
        ),
    ]
