# Generated by Django 5.1 on 2024-09-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='defaults/default_user.svg', upload_to='userProfilePictures/')),
                ('preference_tags', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
