# Generated by Django 5.1 on 2024-09-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user'),
        ('songsManager', '0004_alter_song_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_songs',
            field=models.ManyToManyField(blank=True, null=True, to='songsManager.song'),
        ),
    ]
