# Generated by Django 5.1 on 2024-09-21 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songsManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_pic', models.ImageField(blank=True, null=True, upload_to='playlistProfilePics/')),
                ('title', models.CharField(default='My Playlist', max_length=200)),
                ('description', models.TextField(default='My playlist', max_length=800)),
                ('is_public', models.BooleanField(default=False)),
                ('songs', models.ManyToManyField(blank=True, to='songsManager.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
